Deep Learning With PyTorch - Full Course<br>
https://www.youtube.com/watch?v=c36lUUr864M

In [2]:
import torch

In [3]:
x = torch.zeros(2,3)

In [4]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
y = torch.empty(2,2,2,2)

In [6]:
print(y)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


In [7]:
print(x.size())

torch.Size([2, 3])


In [8]:
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x, y)

tensor([[0.9314, 0.9446, 0.5427],
        [0.1607, 0.5202, 0.7499],
        [0.6395, 0.2762, 0.7207]]) tensor([[0.4840, 0.8097, 0.5377],
        [0.8084, 0.6569, 0.5476],
        [0.2563, 0.1226, 0.3059]])
